common: &common
  dialect: mysql
  dir: ./backend/database/migration
  table: migrations

lcl-docker:
  <<: *common
  # datasource: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${DATABASE_NAME}?parseTime=true
  datasource: root:gacha@tcp(127.0.0.1:7895)/gacha_db?parseTime=true